### ISSUE TITLE
Site backbone

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/shinny-dvor#2]
### С чем связан запрос на фичу?

Сверстать каркас для сайта

[Дизайн](https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=0%3A1)

### Расскажите как вы это себе видите

Структура проекта:

\- site
|_ index-page
|_ *-fragment
|_ *-fragment
|_ *-fragment

Все фрагменты и страницы - внутри папки site по маске выше

**Выполнять по порядку, на каждый пункт делать коммит**

- [x] Разделить сайт на фрагменты (создать для каждого фрагмента по воркспейсу, без кода)
- [x] Создать пакет с главной страницей (index-page). Она будет отдаваться по роуту `/` (`export { default } from '@site/index-page'`). Как пруф что все работает - отрисовать что-нибудь
- [x] Сверстать скелет для фрагментов и разместить их на странице. Это должны быть контейнеры, в которых потом будет размещаться контент. В будущем, код написанный на этой стадии не должен меняться

### Приложите примеры реализаций

https://github.com/torin-asakura/misik/tree/master/landing

**Comment by ikorol3107** [comment]
@TFK70 
- _"Сверстать скелет для фрагментов и разместить их на странице. Это должны быть контейнеры, в которых потом будет размещаться контент. В будущем, код написанный на этой стадии не должен меняться"_  - на этом этапе должен быть скелет только для index-page или для всех страниц (страница Контакты, Блог, Услуги и тд)?

**Comment by TFK70** [comment]
> @TFK70
> 
> * _"Сверстать скелет для фрагментов и разместить их на странице. Это должны быть контейнеры, в которых потом будет размещаться контент. В будущем, код написанный на этой стадии не должен меняться"_  - на этом этапе должен быть скелет только для index-page или для всех страниц (страница Контакты, Блог, Услуги и тд)?

Для всех
