### ISSUE TITLE
Site stylization

### ISSUE THREAD

**Issue by TFK70** [torin-asakura/shinny-dvor#4]
### Задача

Наполнить скелет сайта данными

### Что именно должно быть

- [x] Вынести blog как отдельное приложение (сейчас это как страница)
- [x] Инициализировать ui компоненты
- [x] Применить стили на скелет, наполнить контейнеры элементами

**Comment by ikorol3107** [comment]
Доделать:
1) некликабельны последние статьи на главной странице 
https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=529%3A1728
2) Цвет текста у Link в футере не черный в десктопной версии.
3) нет нижнего подчеркивания у navigation items при активном состоянии.
4) нет логики перехода из списка статей в блоге на конкретную статью. Сейчас просто переходит на страницу Article не передавая в пропсах данные статьи. В services то же самое.
5) не кликабельны "статьи для услуги":
https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=529%3A4688
6) пока не готов аккордеон можно сделать для него блок с вложеными примерами работ:
https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=474%3A1185
7) Switch для мобильной версии Service должен быть другой (с иконкой в кнопке)
https://www.figma.com/file/vqze2qxVpYJDKtablQExoA/%D0%A8%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B4%D0%B2%D0%BE%D1%80?node-id=601%3A3433
8) в футере адрес и тел должны быть колонками: не хватает вторых строк с текстом другого цвета
9) в Card нет иконки Close

**Comment by TFK70** [comment]
[Migrated](https://github.com/torin-asakura/shinny-dvor/issues/10)
